import { CollectionType } from "./collection-type";

export enum HeimdallStageType {
    UNZIP_FILES = 'UNZIP_FILES',
    OCR = 'OCR',
    EXTRACT_RECORDS_STRUCTURED_FILES = 'EXTRACT_RECORDS_STRUCTURED_FILES',
    SPEECH_TO_TEXT = 'SPEECH_TO_TEXT',
    TEXT_TO_SPEECH = 'TEXT_TO_SPEECH',
    LANGUAGE_DETECTION = 'LANGUAGE_DETECTION',
    SUMMARIZATION = 'SUMMARIZATION',
    ENTITY_EXTRACTION = 'ENTITY_EXTRACTION',
    TITLE_GENERATION = 'TITLE_GENERATION',
    EXTRACT_CPF_REGEX = 'EXTRACT_CPF_REGEX',
    EXTRACT_CNPJ_REGEX = 'EXTRACT_CNPJ_REGEX',
    EXTRACT_RG_REGEX = 'EXTRACT_RG_REGEX',
    EXTRACT_DATE_REGEX = 'EXTRACT_DATE_REGEX',
    EXTRACT_PHONE_REGEX = 'EXTRACT_PHONE_REGEX',
    EXTRACT_CEP_REGEX = 'EXTRACT_CEP_REGEX',
    EXTRACT_EMAIL_REGEX = 'EXTRACT_EMAIL_REGEX',
    EXTRACT_IP_ADDRESS_REGEX = 'EXTRACT_IP_ADDRESS_REGEX',
    EXTRACT_MAC_ADDRESS_REGEX = 'EXTRACT_MAC_ADDRESS_REGEX',
    EXTRACT_MONEY_REGEX = 'EXTRACT_MONEY_REGEX',
    EXTRACT_WEIGHT_REGEX = 'EXTRACT_WEIGHT_REGEX',
    EXTRACT_DISTANCE_REGEX = 'EXTRACT_DISTANCE_REGEX',
    EXTRACT_TIME_REGEX = 'EXTRACT_TIME_REGEX',
    EXTRACT_CAR_PLATE_REGEX = 'EXTRACT_CAR_PLATE_REGEX',
    EXTRACT_EAN13_REGEX = 'EXTRACT_EAN13_REGEX',
    EXTRACT_EAN8_REGEX = 'EXTRACT_EAN8_REGEX',
    EXTRACT_ISBN_REGEX = 'EXTRACT_ISBN_REGEX',
    EXTRACT_BANK_INFO_REGEX = 'EXTRACT_BANK_INFO_REGEX',
    EXTRACT_CRYPTO_WALLET_REGEX = 'EXTRACT_CRYPTO_WALLET_REGEX',
}

export const HeimdallStageIndexationMap = {
    // [HeimdallStageType.UNZIP_FILES]: {
    //     id: HeimdallStageType.UNZIP_FILES,
    //     titleKey: 'unzipFilesTitle',
    //     descriptionKey: 'unzipFilesDescription',
    //     icon: 'pi pi-folder-open',
    //     collectionTypes: [CollectionType.FILESYSTEM],
    // },
    // [HeimdallStageType.OCR]: {
    //     id: HeimdallStageType.OCR,
    //     titleKey: 'ocrTitle',
    //     descriptionKey: 'ocrDescription',
    //     icon: 'pi pi-camera',
    //     collectionTypes: [CollectionType.FILESYSTEM],
    // },
    [HeimdallStageType.EXTRACT_RECORDS_STRUCTURED_FILES]: {
        id: HeimdallStageType.EXTRACT_RECORDS_STRUCTURED_FILES,
        titleKey: 'extractStructuredFilesTitle',
        descriptionKey: 'extractStructuredFilesDescription',
        icon: 'pi pi-file',
        collectionTypes: [CollectionType.FILESYSTEM],
    },
    [HeimdallStageType.SPEECH_TO_TEXT]: {
        id: HeimdallStageType.SPEECH_TO_TEXT,
        titleKey: 'speechToTextTitle',
        descriptionKey: 'speechToTextDescription',
        icon: 'pi pi-volume-up',
        collectionTypes: [CollectionType.FILESYSTEM],
    },
    // [HeimdallStageType.TEXT_TO_SPEECH]: {
    //     id: HeimdallStageType.TEXT_TO_SPEECH,
    //     titleKey: 'textToSpeechTitle',
    //     descriptionKey: 'textToSpeechDescription',
    //     icon: 'pi pi-comment',
    //     collectionTypes: [
    //         CollectionType.DATABASE,
    //         CollectionType.FILESYSTEM,
    //         CollectionType.MONGODB,
    //         CollectionType.REST_API,
    //         CollectionType.PENLINK,
    //     ],
    // },
    // [HeimdallStageType.LANGUAGE_DETECTION]: {
    //     id: HeimdallStageType.LANGUAGE_DETECTION,
    //     titleKey: 'languageDetectionTitle',
    //     descriptionKey: 'languageDetectionDescription',
    //     icon: 'pi pi-globe',
    //     collectionTypes: [
    //         CollectionType.DATABASE,
    //         CollectionType.FILESYSTEM,
    //         CollectionType.MONGODB,
    //         CollectionType.REST_API,
    //         CollectionType.PENLINK,
    //     ],
    // },
    [HeimdallStageType.SUMMARIZATION]: {
        id: HeimdallStageType.SUMMARIZATION,
        titleKey: 'summarizationTitle',
        descriptionKey: 'summarizationDescription',
        icon: 'pi pi-align-left',
        collectionTypes: [
            CollectionType.DATABASE,
            CollectionType.FILESYSTEM,
            CollectionType.MONGODB,
            CollectionType.REST_API,
            CollectionType.PENLINK,
        ],
    },
    [HeimdallStageType.ENTITY_EXTRACTION]: {
        id: HeimdallStageType.ENTITY_EXTRACTION,
        titleKey: 'entityExtractionTitle',
        descriptionKey: 'entityExtractionDescription',
        icon: 'pi pi-user',
        collectionTypes: [
            CollectionType.DATABASE,
            CollectionType.FILESYSTEM,
            CollectionType.MONGODB,
            CollectionType.REST_API,
            CollectionType.PENLINK,
        ],
    },
    [HeimdallStageType.TITLE_GENERATION]: {
        id: HeimdallStageType.TITLE_GENERATION,
        titleKey: 'titleGenerationTitle',
        descriptionKey: 'titleGenerationDescription',
        icon: 'pi pi-pencil',
        collectionTypes: [
            CollectionType.DATABASE,
            CollectionType.FILESYSTEM,
            CollectionType.MONGODB,
            CollectionType.REST_API,
            CollectionType.PENLINK,
        ],
    },
    [HeimdallStageType.EXTRACT_CPF_REGEX]: {
        id: HeimdallStageType.EXTRACT_CPF_REGEX,
        titleKey: 'extractCpfRegexTitle',
        descriptionKey: 'extractCpfRegexDescription',
        icon: 'pi pi-id-card',
        collectionTypes: [
            CollectionType.DATABASE,
            CollectionType.FILESYSTEM,
            CollectionType.MONGODB,
            CollectionType.REST_API,
            CollectionType.PENLINK,
        ],
    },
    [HeimdallStageType.EXTRACT_CNPJ_REGEX]: {
        id: HeimdallStageType.EXTRACT_CNPJ_REGEX,
        titleKey: 'extractCnpjRegexTitle',
        descriptionKey: 'extractCnpjRegexDescription',
        icon: 'pi pi-briefcase',
        collectionTypes: [
            CollectionType.DATABASE,
            CollectionType.FILESYSTEM,
            CollectionType.MONGODB,
            CollectionType.REST_API,
            CollectionType.PENLINK,
        ],
    },
    [HeimdallStageType.EXTRACT_RG_REGEX]: {
        id: HeimdallStageType.EXTRACT_RG_REGEX,
        titleKey: 'extractRgRegexTitle',
        descriptionKey: 'extractRgRegexDescription',
        icon: 'pi pi-id-card',
        collectionTypes: [
            CollectionType.DATABASE,
            CollectionType.FILESYSTEM,
            CollectionType.MONGODB,
            CollectionType.REST_API,
            CollectionType.PENLINK,
        ],
    },
    [HeimdallStageType.EXTRACT_DATE_REGEX]: {
        id: HeimdallStageType.EXTRACT_DATE_REGEX,
        titleKey: 'extractDateRegexTitle',
        descriptionKey: 'extractDateRegexDescription',
        icon: 'pi pi-calendar',
        collectionTypes: [
            CollectionType.DATABASE,
            CollectionType.FILESYSTEM,
            CollectionType.MONGODB,
            CollectionType.REST_API,
            CollectionType.PENLINK,
        ],
    },
    [HeimdallStageType.EXTRACT_PHONE_REGEX]: {
        id: HeimdallStageType.EXTRACT_PHONE_REGEX,
        titleKey: 'extractPhoneRegexTitle',
        descriptionKey: 'extractPhoneRegexDescription',
        icon: 'pi pi-phone',
        collectionTypes: [
            CollectionType.DATABASE,
            CollectionType.FILESYSTEM,
            CollectionType.MONGODB,
            CollectionType.REST_API,
            CollectionType.PENLINK,
        ],
    },
    [HeimdallStageType.EXTRACT_CEP_REGEX]: {
        id: HeimdallStageType.EXTRACT_CEP_REGEX,
        titleKey: 'extractCepRegexTitle',
        descriptionKey: 'extractCepRegexDescription',
        icon: 'pi pi-map-marker',
        collectionTypes: [
            CollectionType.DATABASE,
            CollectionType.FILESYSTEM,
            CollectionType.MONGODB,
            CollectionType.REST_API,
            CollectionType.PENLINK,
        ],
    },
    [HeimdallStageType.EXTRACT_EMAIL_REGEX]: {
        id: HeimdallStageType.EXTRACT_EMAIL_REGEX,
        titleKey: 'extractEmailRegexTitle',
        descriptionKey: 'extractEmailRegexDescription',
        icon: 'pi pi-envelope',
        collectionTypes: [
            CollectionType.DATABASE,
            CollectionType.FILESYSTEM,
            CollectionType.MONGODB,
            CollectionType.REST_API,
            CollectionType.PENLINK,
        ],
    },
    [HeimdallStageType.EXTRACT_IP_ADDRESS_REGEX]: {
        id: HeimdallStageType.EXTRACT_IP_ADDRESS_REGEX,
        titleKey: 'extractIpAddressRegexTitle',
        descriptionKey: 'extractIpAddressRegexDescription',
        icon: 'pi pi-sitemap',
        collectionTypes: [
            CollectionType.DATABASE,
            CollectionType.FILESYSTEM,
            CollectionType.MONGODB,
            CollectionType.REST_API,
            CollectionType.PENLINK,
        ],
    },
    [HeimdallStageType.EXTRACT_MAC_ADDRESS_REGEX]: {
        id: HeimdallStageType.EXTRACT_MAC_ADDRESS_REGEX,
        titleKey: 'extractMacAddressRegexTitle',
        descriptionKey: 'extractMacAddressRegexDescription',
        icon: 'pi pi-sitemap',
        collectionTypes: [
            CollectionType.DATABASE,
            CollectionType.FILESYSTEM,
            CollectionType.MONGODB,
            CollectionType.REST_API,
            CollectionType.PENLINK,
        ],
    },
    [HeimdallStageType.EXTRACT_MONEY_REGEX]: {
        id: HeimdallStageType.EXTRACT_MONEY_REGEX,
        titleKey: 'extractMoneyRegexTitle',
        descriptionKey: 'extractMoneyRegexDescription',
        icon: 'pi pi-dollar',
        collectionTypes: [
            CollectionType.DATABASE,
            CollectionType.FILESYSTEM,
            CollectionType.MONGODB,
            CollectionType.REST_API,
            CollectionType.PENLINK,
        ],
    },
    [HeimdallStageType.EXTRACT_WEIGHT_REGEX]: {
        id: HeimdallStageType.EXTRACT_WEIGHT_REGEX,
        titleKey: 'extractWeightRegexTitle',
        descriptionKey: 'extractWeightRegexDescription',
        icon: 'pi pi-chart-bar',
        collectionTypes: [
            CollectionType.DATABASE,
            CollectionType.FILESYSTEM,
            CollectionType.MONGODB,
            CollectionType.REST_API,
            CollectionType.PENLINK,
        ],
    },
    [HeimdallStageType.EXTRACT_DISTANCE_REGEX]: {
        id: HeimdallStageType.EXTRACT_DISTANCE_REGEX,
        titleKey: 'extractDistanceRegexTitle',
        descriptionKey: 'extractDistanceRegexDescription',
        icon: 'pi pi-compass',
        collectionTypes: [
            CollectionType.DATABASE,
            CollectionType.FILESYSTEM,
            CollectionType.MONGODB,
            CollectionType.REST_API,
            CollectionType.PENLINK,
        ],
    },
    [HeimdallStageType.EXTRACT_TIME_REGEX]: {
        id: HeimdallStageType.EXTRACT_TIME_REGEX,
        titleKey: 'extractTimeRegexTitle',
        descriptionKey: 'extractTimeRegexDescription',
        icon: 'pi pi-clock',
        collectionTypes: [
            CollectionType.DATABASE,
            CollectionType.FILESYSTEM,
            CollectionType.MONGODB,
            CollectionType.REST_API,
            CollectionType.PENLINK,
        ],
    },
    [HeimdallStageType.EXTRACT_CAR_PLATE_REGEX]: {
        id: HeimdallStageType.EXTRACT_CAR_PLATE_REGEX,
        titleKey: 'extractCarPlateRegexTitle',
        descriptionKey: 'extractCarPlateRegexDescription',
        icon: 'pi pi-car',
        collectionTypes: [
            CollectionType.DATABASE,
            CollectionType.FILESYSTEM,
            CollectionType.MONGODB,
            CollectionType.REST_API,
            CollectionType.PENLINK,
        ],
    },
    [HeimdallStageType.EXTRACT_EAN13_REGEX]: {
        id: HeimdallStageType.EXTRACT_EAN13_REGEX,
        titleKey: 'extractEan13RegexTitle',
        descriptionKey: 'extractEan13RegexDescription',
        icon: 'pi pi-bars',
        collectionTypes: [
            CollectionType.DATABASE,
            CollectionType.FILESYSTEM,
            CollectionType.MONGODB,
            CollectionType.REST_API,
            CollectionType.PENLINK,
        ],
    },
    [HeimdallStageType.EXTRACT_EAN8_REGEX]: {
        id: HeimdallStageType.EXTRACT_EAN8_REGEX,
        titleKey: 'extractEan8RegexTitle',
        descriptionKey: 'extractEan8RegexDescription',
        icon: 'pi pi-bars',
        collectionTypes: [
            CollectionType.DATABASE,
            CollectionType.FILESYSTEM,
            CollectionType.MONGODB,
            CollectionType.REST_API,
            CollectionType.PENLINK,
        ],
    },
    [HeimdallStageType.EXTRACT_ISBN_REGEX]: {
        id: HeimdallStageType.EXTRACT_ISBN_REGEX,
        titleKey: 'extractIsbnRegexTitle',
        descriptionKey: 'extractIsbnRegexDescription',
        icon: 'pi pi-book',
        collectionTypes: [
            CollectionType.DATABASE,
            CollectionType.FILESYSTEM,
            CollectionType.MONGODB,
            CollectionType.REST_API,
            CollectionType.PENLINK,
        ],
    },
    [HeimdallStageType.EXTRACT_BANK_INFO_REGEX]: {
        id: HeimdallStageType.EXTRACT_BANK_INFO_REGEX,
        titleKey: 'extractBankInfoRegexTitle',
        descriptionKey: 'extractBankInfoRegexDescription',
        icon: 'pi pi-credit-card',
        collectionTypes: [
            CollectionType.DATABASE,
            CollectionType.FILESYSTEM,
            CollectionType.MONGODB,
            CollectionType.REST_API,
            CollectionType.PENLINK,
        ],
    },
    [HeimdallStageType.EXTRACT_CRYPTO_WALLET_REGEX]: {
        id: HeimdallStageType.EXTRACT_CRYPTO_WALLET_REGEX,
        titleKey: 'extractCryptoWalletRegexTitle',
        descriptionKey: 'extractCryptoWalletRegexDescription',
        icon: 'pi pi-bitcoin',
        collectionTypes: [
            CollectionType.DATABASE,
            CollectionType.FILESYSTEM,
            CollectionType.MONGODB,
            CollectionType.REST_API,
            CollectionType.PENLINK,
        ],
    },
};


